### ISSUE TITLE
[NEW] Page / Page Header

### ISSUE THREAD

**Issue by resir014** [kata-ai/aksara-ui#419]
### Page Header

- [x] change button to dropdownButton (Update stories)

#### Filter section

- [x] order select input is dynamic , 0...* (need to confirm is there any maximum order select input), max 2
- [x] adding filter button
- [x] maximum tag filter = 6, more than it use `x+ Filter` label
- [x] show filter tags
- [x] `x+ Filter` tags component
- [x] when `x+ Filter` is clicked, show popover

#### Sub Header
- [x] component
- [x] stories

### Issues
- [x] Pill Component doesn't have onClickRemove Handler (resolved, using onClick)

**Comment by neveraemje** [comment]
- Missed subheader variant
- Missed page header with filter kit
- Recheck Figma ya

**Comment by zanuarmirza** [comment]
# TODO
## Page Header
- [ ] change button to dropdownButton (Update stories)
### Filter section

- [ ] order select input is dynamic , 0...* (need to confirm is there any maximum order select input)
- [ ] adding filter button
- [ ] maximum tag filter = 6, more than it use `x+ Filter` label

**used component** 
- searchbox
- selectfield

**Comment by zanuarmirza** [comment]
## Additional Information
When `Filter Button` is pressed, show drawer filter section

**Comment by zanuarmirza** [comment]
### Update
- [x] fix spacing at Subheader
