### ISSUE TITLE
Action List

### ISSUE THREAD

**Issue by neveraemje** [kata-ai/aksara-ui#597]
### TODO

- [x] ActionList
- [x] ActionListItem

### ActionList
- [x] space 4px vertical
- [x] Border radius using 8px
- [x] horizontal padding 0, use margin from item to create 12px space, because inside actionList can be filled with full horizontally separator
- [x] inner padding left and right 12px. 
- [x] Kursor change to pointer
- [x] When hovering on active state, nothing hover style.

**Comment by neveraemje** [comment]
- inner padding left and right 12px. 
- Kursor change to pointer
- When hovering on active state, nothing hover style.
@zanuarmirza

**Comment by neveraemje** [comment]
- On State Active, Text position not same with another state.
